import test from "node:test";
import assert from "node:assert/strict";
import { newSave, battleTurn, catchChance, validateSave, type Battle } from "../src/game";
import { REGIONS, REGION_BY_ID, SPECIES, createNuvo, maxHp } from "../src/data";
import { ORBS, orbAffinity, orbCount, awardCrewXp, reorderCrew, keeperDefeat, restoreAtLodge, TRAINERS, trainerBattle, DREAM_CHANCE, LEAGUE_GUARDIANS } from "../src/expansion";
import { enterInterior, leaveInterior } from "../src/adventure";
import { canWalk, findPath, getMap } from "../src/World";
import { nuvoAtlas, gaitFor } from "../src/spriteMotion";
const fresh=()=>newSave({name:"Test",palette:0,pronouns:"They / them"},"spriglet");
test("exhausted trainer crews can struggle and reloaded fainted crews get a last stand",()=>{
  const save=fresh(), trainer=TRAINERS[0], battle=trainerBattle(save,trainer);
  assert.ok(battleTurn(save,battle,{type:"struggle"}).error);
  for(const move of save.party[0].moves)save.party[0].pp[move]=0;
  const result=battleTurn(save,battle,{type:"struggle"},()=>.5);
  assert.equal(result.error,undefined);assert.ok(result.battle.wild.hp<battle.wild.hp);assert.ok(result.save.party[0].hp<save.party[0].hp);
  save.party[0].hp=0;assert.equal(trainerBattle(save,trainer).lastStand,"choice");
});
test("five new frontier regions plus a hidden dimension have accessible services",()=>{
  assert.equal(REGIONS.filter(r=>!r.hidden).length,14);assert.equal(REGION_BY_ID.dreamland.hidden,true);assert.deepEqual(REGION_BY_ID.dreamland.links,{});
  for(const region of REGIONS.filter(r=>r.kind==="Town")) {
    const props=getMap(region);for(const kind of ["tailor","barber","league"]){const prop=props.find(p=>p.interact===kind)!;assert.ok(prop);assert.ok(findPath(560,496,prop.x*32,prop.y*32+48,region).length,`${region.id} ${kind}`);}
    for(const room of ["tailor","barber"] as const){const s=enterInterior({...fresh(),region:region.id},room,288,336);assert.ok(validateSave(s));assert.ok(findPath(s.x,s.y,576,368,region,room).length);assert.equal(leaveInterior(s).x,288);}
  }
});
test("drag reorder preserves identities and makes the far-left Nuvo active",()=>{const s=fresh();s.party.push(createNuvo("cindlet"),createNuvo("bubbfin"));const reordered=reorderCrew(s,2,0);assert.equal(reordered.party[0].uid,s.party[2].uid);assert.equal(reordered.party[1].uid,s.party[0].uid);assert.equal(reorderCrew(s,4,0),s);assert.equal(reorderCrew(s,0,-1),s);assert.ok(validateSave(reordered));});
test("crew receives 20 percent XP including fainted members without reviving them",()=>{const party=[createNuvo("spriglet",5),createNuvo("cindlet",5),createNuvo("bubbfin",5)];party[2].hp=0;const result=awardCrewXp(party,0,50);assert.equal(result[0].xp,50);assert.equal(result[1].xp,10);assert.equal(result[2].xp,10);assert.equal(result[2].hp,0);assert.equal(awardCrewXp(party,0,1000)[2].hp,0);assert.equal(party[0].xp,0);});
test("specialty orbs use their own inventory, affinities and first-turn rule",()=>{const s=fresh();const wild=createNuvo("bubbfin",3,false);const b:Battle={wild,active:0,turn:0,log:[],reward:0};assert.equal(orbAffinity(wild,"tide",0),1.7);assert.equal(orbAffinity(wild,"swift",0),2);assert.equal(orbAffinity(wild,"swift",1),1);assert.ok(catchChance(wild,"tide")>catchChance(wild));assert.ok(battleTurn(s,b,{type:"catch",orb:"tide"}).error);s.specialOrbs={tide:2};const r=battleTurn(s,b,{type:"catch",orb:"tide"},()=>0);assert.equal(r.save.orbs,s.orbs);assert.equal(orbCount(r.save,"tide"),1);assert.equal(r.battle.over,"caught");assert.ok(validateSave(r.save));assert.equal(ORBS.length,6);});
test("trainers have real reachable encounters, queues and uncapturable bonded Nuvo",()=>{assert.equal(TRAINERS.length,14);for(const t of TRAINERS){const s={...fresh(),region:t.region};const b=trainerBattle(s,t);assert.ok(findPath(560,496,t.x*32,t.y*32,REGION_BY_ID[t.region]).length);assert.ok(battleTurn(s,b,{type:"catch"}).error);assert.ok(battleTurn(s,b,{type:"run"}).error);assert.equal(b.trainerName,t.name);}const s=fresh();s.party=[createNuvo("cindlet-3",50,false)];const t=TRAINERS.find(t=>t.region==="verdant")!;let b=trainerBattle(s,t);b.wild.hp=1;let r=battleTurn(s,b,{type:"move",id:s.party[0].moves.find(id=>id==="flame-9")!},()=>0);assert.equal(r.battle.over,undefined);assert.equal(r.battle.opponentQueue?.length,0);r.battle.wild.hp=1;const done=battleTurn(r.save,r.battle,{type:"move",id:"flame-9"},()=>0);assert.equal(done.battle.over,"won");assert.ok(done.save.defeatedTrainers?.includes(t.id));});
test("keeper last stand has HP, attacks, rescue, and deterministic rare Dream Land outcome",()=>{const s=fresh();s.party[0].hp=0;const b:Battle={wild:createNuvo("cindlet",45,false),active:0,turn:0,log:[],reward:0,lastStand:"choice"};assert.ok(battleTurn(s,b,{type:"move",id:"bloom-0"}).error);const stand=battleTurn(s,b,{type:"stand"});assert.equal(stand.battle.lastStand,"fighting");assert.ok(stand.battle.keeperHp!>0);stand.battle.keeperHp=1;const dream=battleTurn(stand.save,stand.battle,{type:"strike"},()=>0);assert.equal(dream.battle.over,"lost");assert.equal(dream.save.region,"dreamland");assert.ok(dream.battle.dreamAwakening);assert.ok(validateSave(dream.save));const ordinary=keeperDefeat({...s,lastLodge:"crownspire"},()=>DREAM_CHANCE);assert.equal(ordinary.dream,false);assert.equal(ordinary.save.region,"crownspire");assert.equal(ordinary.save.interior,"lodge");assert.equal(keeperDefeat({...s,region:"dreamland"},()=>0).dream,false);assert.equal(restoreAtLodge(dream.save).region,"mossbell");});
test("all evolved forms use separate atlas cells and every Nuvo has a movement gait",()=>{const evolved=SPECIES.filter(s=>s.stage>0);assert.equal(new Set(evolved.map(s=>`${nuvoAtlas(s)}:${s.sprite}`)).size,150);for(const s of SPECIES)assert.ok(["walk","float","swim","hop"].includes(gaitFor(s.id)));assert.equal(nuvoAtlas(SPECIES.find(s=>s.id==="oneirune")!),"oneirune.png");for(const g of LEAGUE_GUARDIANS)assert.ok(SPECIES.some(s=>s.id===g.species));});
test("new customization and orb fields validate while legacy saves still work",()=>{const s=fresh();assert.ok(validateSave(s));assert.ok(validateSave({...s,player:{...s.player,outfit:5,hair:5,hairColor:5},specialOrbs:{prism:10},wardrobe:[0,5]}));assert.equal(validateSave({...s,player:{...s.player,hair:6}}),false);assert.equal(validateSave({...s,specialOrbs:{prism:-1}}),false);});
