import { writeFileSync } from "node:fs";
import { SPECIES, MOVES } from "../src/data";
import { LEAGUE_GUARDIANS } from "../src/expansion";
const quote=(value:unknown)=>`'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
const rows=[...SPECIES.map(s=>`('species','${s.id}',${quote({stats:s.stats,types:s.types,learnset:s.learnset})})`),...MOVES.map(m=>`('move','${m.id}',${quote(m)})`),...LEAGUE_GUARDIANS.map(g=>`('guardian','${g.id}',${quote(g)})`)];
writeFileSync("supabase/migrations/202609280002_league_catalog.sql",`-- Generated by scripts/export-league.ts; authoritative battle catalog.\ninsert into public.league_catalog(kind,id,data) values\n${rows.join(",\n")}\non conflict(kind,id) do update set data=excluded.data;\n`);
