const $=id=>document.getElementById(id), attached=new Map(), urls=new Map();
let pending=[], db=null, noticeTimer, exporting=false;
function tell(message){$('notice').textContent=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').textContent='',7000);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function copy(text){try{await navigator.clipboard.writeText(text);tell('Copied. Paste into Suno.');}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();tell(ok?'Copied. Paste into Suno.':'Select the prompt text on the card and copy it.');}}
function element(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;}
function button(text,action){const b=element('button','',text);b.type='button';b.onclick=action;return b;}
function persist(id){if(!db)return;try{const tx=db.transaction('tracks','readwrite');if(attached.has(id))tx.objectStore('tracks').put({id,...attached.get(id)});else tx.objectStore('tracks').delete(id);tx.onerror=()=>{$('storage-status').textContent='Storage is full. Export a ZIP before closing.';};}catch{$('storage-status').textContent='Export a ZIP before closing to keep your attachments.';}}
function remove(id){attached.delete(id);if(urls.has(id))URL.revokeObjectURL(urls.get(id));urls.delete(id);persist(id);render();}
function assign(id,file){if(!/\.(mp3|wav|m4a|ogg|flac)$/i.test(file.name)){tell('Choose an MP3, WAV, M4A, OGG or FLAC audio file.');return;}if(file.size>150*1024*1024||file.size<500){tell('Each track must be between 500 bytes and 150 MB. MP3 is easiest for larger batches.');return;}const total=[...attached].filter(([key])=>key!==id).reduce((sum,[,v])=>sum+v.file.size,0);if(total+file.size>500*1024*1024){tell('This batch is over 500 MB. Export a smaller batch or use MP3 downloads.');return;}if(urls.has(id))URL.revokeObjectURL(urls.get(id));urls.delete(id);attached.set(id,{file,originalName:file.name,notes:'',loopStart:'',loopEnd:''});persist(id);render();}
function normalized(value){return value.toLowerCase().replace(/[^a-z0-9]/g,'');}
function accept(files){for(const file of files){const name=normalized(file.name.replace(/\.[^.]+$/,''));const cue=CUES.find(c=>name===normalized(c.id)||name===normalized('nuvori'+c.id)||name===normalized(c.title)||name===normalized('nuvori'+c.title));if(cue&&!attached.has(cue.id))assign(cue.id,file);else pending.push(file);}renderPending();}
function setupDrop(node,callback){node.ondragover=e=>{e.preventDefault();node.classList.add('dragover');};node.ondragleave=()=>node.classList.remove('dragover');node.ondrop=e=>{e.preventDefault();e.stopPropagation();node.classList.remove('dragover');callback([...e.dataTransfer.files]);};}
function renderPending(){$('pending').replaceChildren();$('pending').hidden=!pending.length;if(!pending.length)return;$('pending').append(element('strong','','Choose where these tracks belong'));pending.forEach((file,index)=>{const row=element('div','pending-row');row.append(element('span','',file.name));const select=element('select');select.setAttribute('aria-label','Assign '+file.name);select.append(new Option('Choose a theme…',''));CUES.forEach(c=>select.append(new Option(`${attached.has(c.id)?'Replace: ':''}${c.title}`,c.id)));row.append(select,button('Assign',()=>{if(!select.value)return;assign(select.value,file);pending.splice(index,1);renderPending();}),button('Dismiss',()=>{pending.splice(index,1);renderPending();}));$('pending').append(row);});}
function render(){const query=$('search').value.toLowerCase(),filter=$('filter').value;$('cards').replaceChildren();$('progress').textContent=`${attached.size} of ${CUES.length} themes attached · ${Math.round([...attached.values()].reduce((n,v)=>n+v.file.size,0)/1048576)} MB`;$('export').disabled=!attached.size||exporting;
CUES.forEach((cue,index)=>{const track=attached.get(cue.id);if(query&&!`${cue.id} ${cue.title} ${cue.use}`.toLowerCase().includes(query))return;if(filter==='priority'&&!cue.priority||filter==='missing'&&track||filter==='ready'&&!track)return;
const card=element('article','card'+(track?' ready':'')),top=element('div','card-top');top.append(element('span','number',String(index+1).padStart(2,'0')),element('span','badge',track?'✓ Attached':cue.priority?'★ Start here':'Theme'));card.append(top,element('h2','',cue.title),element('div','use',cue.use),element('p','prompt',cue.prompt));const actions=element('div','actions');actions.append(button('Copy style prompt',()=>copy(cue.prompt)),button('Copy title',()=>copy('Nuvori — '+cue.title)));card.append(actions);
const info=element('div','file-info');info.append(element('div','filename',cue.id+'.mp3'));if(track){info.append(element('div','file-name',track.originalName||track.file.name));const audio=document.createElement('audio');audio.controls=true;audio.preload='none';if(!urls.has(cue.id))urls.set(cue.id,URL.createObjectURL(track.file));audio.src=urls.get(cue.id);audio.onerror=()=>tell('This browser cannot preview that format. The file can still be included in your handoff.');audio.onplay=()=>document.querySelectorAll('audio').forEach(other=>{if(other!==audio)other.pause();});info.append(audio);
const details=element('details'),summary=element('summary','','Optional notes & loop points');details.append(summary);const row=element('div','loop-row');for(const [key,label]of [['loopStart','Loop start (seconds)'],['loopEnd','Loop end (seconds)']]){const l=element('label','',label),input=document.createElement('input');input.type='number';input.min='0';input.step='.01';input.placeholder='Auto';input.value=track[key];input.onchange=()=>{track[key]=input.value;persist(cue.id);};l.append(input);row.append(l);}const notes=document.createElement('textarea');notes.placeholder='Favorite section, trim requests, alternate take…';notes.setAttribute('aria-label','Notes for '+cue.title);notes.value=track.notes;notes.oninput=()=>{track.notes=notes.value;persist(cue.id);};details.append(row,notes);info.append(details);
}else info.append(element('p','empty','Drop your chosen take here, or choose a file.'));
const picker=document.createElement('input');picker.type='file';picker.accept='.mp3,.wav,.m4a,.ogg,.flac';picker.hidden=true;picker.onchange=()=>{if(picker.files[0])assign(cue.id,picker.files[0]);};const controls=element('div','actions');controls.append(button(track?'Replace track':'Choose audio',()=>picker.click()));if(track)controls.append(button('Remove',()=>remove(cue.id)));info.append(controls,picker);card.append(info);setupDrop(card,files=>{if(files[0])assign(cue.id,files[0]);if(files.length>1)accept(files.slice(1));});$('cards').append(card);});}
$('search').oninput=render;$('filter').onchange=render;$('batch').onchange=()=>{accept([...$('batch').files]);$('batch').value='';};setupDrop($('dropzone'),accept);document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>e.preventDefault());$('exclude').textContent=CUES[0].exclude;$('copy-exclude').onclick=()=>copy(CUES[0].exclude);
$('prompts').onclick=()=>{const lines=['# Nuvori · Suno prompts','Custom mode. Instrumental on. Lyrics empty. Paste prompts into Styles.','Exclude: '+CUES[0].exclude,'Download MP3/WAV; attach in the Studio and export one handoff ZIP.'];CUES.forEach(c=>lines.push(`\n## ${c.title}\nUse: ${c.use}\nFilename: ${c.id}.mp3\n\n${c.prompt}\n`));download(new Blob([lines.join('\n\n')],{type:'text/markdown'}),'Nuvori-Suno-Prompts.md');};
$('export').onclick=async()=>{if(exporting)return;exporting=true;$('export').disabled=true;$('export').textContent='Packing your soundtrack…';try{const tracks=[],entries=[];for(const [id,track]of attached){const start=track.loopStart===''?null:Number(track.loopStart),end=track.loopEnd===''?null:Number(track.loopEnd);if(start!==null&&(!Number.isFinite(start)||start<0)||end!==null&&(!Number.isFinite(end)||end<=(start??0)))throw new Error('Check loop points for '+id+'. End must come after start.');const ext=(track.file.name||track.originalName).split('.').pop().toLowerCase(),path=`music/${id}.${ext}`;tracks.push({id,title:CUES.find(c=>c.id===id).title,file:path,originalName:track.originalName,notes:track.notes,loopStart:start,loopEnd:end});entries.push({name:path,data:new Uint8Array(await track.file.arrayBuffer())});}entries.unshift({name:'suno-handoff.json',data:JSON.stringify({schemaVersion:1,project:'Nuvori',provider:'Suno',createdAt:new Date().toISOString(),tracks},null,2)});entries.push({name:'README.txt',data:'Attach this ZIP in the Nuvori conversation. It contains your selected tracks and their game cue assignments. Loop points and notes are in suno-handoff.json. Partial batches are supported.'});download(createZip(entries),'Nuvori-Suno-Handoff.zip');tell('ZIP ready. Attach it in our conversation and I can integrate these tracks.');}catch(error){tell(error.message||'Export failed. Try a smaller batch.');}finally{exporting=false;$('export').textContent='Export handoff ZIP';render();}};
render();try{const request=indexedDB.open('nuvori-music-studio',1);request.onupgradeneeded=()=>request.result.createObjectStore('tracks',{keyPath:'id'});request.onsuccess=()=>{db=request.result;const read=db.transaction('tracks','readonly').objectStore('tracks').getAll();read.onsuccess=()=>{read.result.forEach(({id,...track})=>{if(CUES.some(c=>c.id===id)&&!attached.has(id)){attached.set(id,track);}});render();$('storage-status').textContent='Attachments remembered in this browser. Export a ZIP as your backup.';};};request.onerror=()=>{$('storage-status').textContent='Export a ZIP before closing; browser storage is unavailable.';};}catch{$('storage-status').textContent='Export a ZIP before closing; browser storage is unavailable.';}
