import { useCallback, useEffect, useRef, useState } from "react";
import { Crown, Shield, Swords, Users, ArrowRight, RefreshCw } from "lucide-react";
import { supabase } from "./online";
import { LEAGUE_GUARDIANS } from "./expansion";
import { MOVE_BY_ID, REGION_BY_ID, SPECIES_BY_ID, TYPE_COLORS, type Nuvo } from "./data";
import { Health, Modal, MoveAnimation, NuvoArt, PlayerArt } from "./components";
import { validateSave, type Save, type Player } from "./game";

export interface LeagueMember { user_id:string;name:string;player:Pick<Player,"palette"|"outfit"|"hair"|"hairColor">;party:Nuvo[];active:number;phase:"crew"|"choice"|"keeper"|"out";keeper_hp:number;keeper_max:number;damage:number;claimed:boolean }
export interface Raid {id:string;code:string;host:string;guardian:string;status:"lobby"|"active"|"won"|"lost"|"closed";hp:number;max_hp:number;revision:number;log:string[];members:LeagueMember[];expires_at:string}
interface Room {code:string;guardian:string;host_name:string;players:number}
async function rpc<T>(name:string,args?:Record<string,unknown>):Promise<T> {if(!supabase)throw new Error("Connect your account to enter the Champions League.");const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T;}

export function useLeague(userId?:string,ready=false) {
  const [raid,setRaid]=useState<Raid|null>(null),[error,setError]=useState(""),[loaded,setLoaded]=useState(false);const request=useRef(0);
  useEffect(()=>{const generation=++request.current;setRaid(null);setLoaded(!userId);if(!userId||!ready)return;
    void rpc<Raid|null>("nuvori_league_current").then(r=>{if(request.current===generation){setRaid(r);setError("");}}).catch(e=>{if(request.current===generation)setError(e.message);}).finally(()=>{if(request.current===generation)setLoaded(true);});
    return()=>{request.current++;};
  },[userId,ready]);
  const apply=useCallback((r:Raid|null)=>{setRaid(prev=>r&&prev?.id===r.id&&prev.revision>r.revision?prev:r);},[]);
  useEffect(()=>{if(!raid)return;let alive=true,checking=false;const id=raid.id;
    const poll=async()=>{if(checking||document.visibilityState!=="visible")return;checking=true;try{const r=await rpc<Raid>("nuvori_league_view",{raid:id});if(alive){apply(r);setError("");}}catch(e){if(alive)setError((e as Error).message);}finally{checking=false;}};
    const timer=setInterval(()=>void poll(),1500);return()=>{alive=false;clearInterval(timer);};
  },[raid?.id,apply]);
  return {raid,setRaid:apply,error,loaded};
}

export function LeaguePanel({save,userId,raid,onRaid,onBeforeJoin,onResult,onClose,notify,error}:{save:Save;userId?:string;raid:Raid|null;onRaid:(r:Raid|null)=>void;onBeforeJoin:()=>Promise<void>;onResult:(s:Save)=>void;onClose:()=>void;notify:(s:string)=>void;error:string}) {
  const [rooms,setRooms]=useState<Room[]>([]),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[localError,setError]=useState(""),[animation,setAnimation]=useState<{id:string;key:number}|null>(null);
  const lock=useRef(false);const selected=LEAGUE_GUARDIANS.find(g=>g.id===raid?.guardian);
  const me=raid?.members.find(m=>m.user_id===userId);const leader=me?.party[me.active];
  useEffect(()=>{if(!userId||raid)return;let alive=true;const load=()=>rpc<Room[]>("nuvori_league_rooms",{area:save.region}).then(r=>{if(alive)setRooms(r);}).catch(e=>{if(alive)setError(e.message);});void load();const timer=setInterval(()=>void load(),6000);return()=>{alive=false;clearInterval(timer);};},[userId,save.region,raid?.id]);
  const run=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await work();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
  const join=(trial?:string,room?:string)=>void run(async()=>{await onBeforeJoin();onRaid(await rpc<Raid>("nuvori_league_open",{trial:trial||null,room_code:room||null}));});
  const act=(action:string,choice="")=>void run(async()=>{const result=await rpc<Raid>("nuvori_league_action",{raid:raid!.id,action,choice,nonce:crypto.randomUUID()});onRaid(result);if(action==="move"||action==="strike")setAnimation({id:choice||"metal-1",key:result.revision});});
  const close=()=>{if(raid){notify("Leave the lobby or finish your Champions trial before exploring.");return;}onClose();};
  const finished=raid&&(raid.status==="won"||raid.status==="lost"||me?.phase==="out");
  return <Modal title="Champions League" eyebrow="ONE GUARDIAN. FOUR KEEPERS. A SHARED LEGEND." onClose={close} wide>
    {(localError||error)&&<p className="league-error" role="alert">{localError||error}</p>}
    {!raid?<><div className="league-intro"><Crown size={35}/><div><h3>Challenge the guardians of Auralis</h3><p>Battle alone or alongside up to three other players. Visit a guardian’s town, build your crew, then open a room. Your entire crew participates; only wild Nuvo can be caught.</p></div></div>
      {!userId&&<div className="tip-box"><Users/><p>Sign in with Google or Discord from Online to enter shared trials.</p></div>}
      <div className="guardian-grid">{LEAGUE_GUARDIANS.map(g=><article key={g.id} className={save.region===g.region?"nearby":""} style={{borderColor:g.color}}><div className="guardian-portrait"><NuvoArt id={g.species} size={156}/><span>Lv. {g.level} · {g.hp.toLocaleString()} HP</span></div><span className="eyebrow">{REGION_BY_ID[g.region].name}</span><h3>{g.name}</h3><p>{g.blurb}</p><small>{save.leagueBadges?.includes(g.id)?`✓ ${g.badge} earned`:`Reward: ${g.badge}`}</small><button className="primary-button" disabled={busy||!userId||save.region!==g.region} onClick={()=>join(g.id)}>{save.region===g.region?"Create challenge room":"Travel here to challenge"}<ArrowRight size={14}/></button></article>)}</div>
      {userId&&<section className="league-rooms"><h3>Gather your crew</h3><div className="room-code-entry"><input aria-label="Champions room code" placeholder="Enter 8-character room code" maxLength={8} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="secondary-button" disabled={busy||code.length!==8} onClick={()=>join(undefined,code)}>Join room</button></div><p className="muted">Everyone must be in the guardian’s town. Rooms remain available for 90 minutes.</p>{rooms.length?rooms.map(r=><button className="room-list-item" key={r.code} disabled={busy||r.players>=4} onClick={()=>join(undefined,r.code)}><Users size={18}/><span>{r.host_name} · {LEAGUE_GUARDIANS.find(g=>g.id===r.guardian)?.name}</span><strong>{r.players}/4 · Join</strong></button>):<p className="muted">No open rooms in this town. Create one and share its code with friends.</p>}</section>}
    </>:selected&&me&&leader?<><div className="raid-heading"><div><span className="eyebrow">{selected.name}</span><h3>{SPECIES_BY_ID[selected.species].name}</h3></div><div className="raid-code"><small>ROOM CODE</small><strong>{raid.code}</strong></div></div>
      <div className={`raid-arena ${raid.status==="won"?"victorious":""}`}><div className="raid-orbit"/><NuvoArt id={selected.species} size={250}/><span className="raid-level">GUARDIAN · LV. {selected.level}</span>{animation&&<MoveAnimation moveId={animation.id} animationKey={animation.key}/>}</div>
      <div className="boss-health"><div><strong>{raid.status==="lobby"?"The guardian awaits":raid.status==="won"?"Guardian defeated":raid.status==="lost"?"Trial ended":"Shared guardian health"}</strong><span>{raid.hp.toLocaleString()} / {raid.max_hp.toLocaleString()} HP</span></div><div><i style={{width:`${raid.hp/raid.max_hp*100}%`}}/></div></div>
      <div className="raid-party">{Array.from({length:4},(_,i)=>{const member=raid.members[i];return <article key={member?.user_id||i} className={member?.user_id===userId?"you":""}>{member?<><div><PlayerArt palette={member.player.palette} look={member.player} size={50}/><strong>{member.name}{member.user_id===raid.host?" ♛":""}</strong></div><NuvoArt id={member.party[member.active].speciesId} size={65}/><span>{member.claimed?"Trial complete":member.phase==="choice"?"Choosing last stand":member.phase==="out"?"Awaiting rescue":member.phase==="keeper"?`Keeper · ${member.keeper_hp}/${member.keeper_max} HP`:SPECIES_BY_ID[member.party[member.active].speciesId].name}</span><Health nuvo={member.party[member.active]} showText={member.phase==="crew"}/><small>{member.damage} damage dealt</small></>:<><Users size={32}/><span>Waiting for a keeper</span><small>Share the room code</small></>}</article>;})}</div>
      {raid.status==="lobby"?<div className="expansion-footer"><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{await rpc("nuvori_league_leave",{raid:raid.id});onRaid(null);})}>Leave room</button>{raid.host===userId?<button className="primary-button" disabled={busy} onClick={()=>void run(async()=>onRaid(await rpc<Raid>("nuvori_league_start",{raid:raid.id})))}><Swords size={18}/> Begin with {raid.members.length} keeper{raid.members.length===1?"":"s"}</button>:<p>Waiting for the host to begin…</p>}</div>
      :finished?<div className="raid-result"><Crown size={28}/><h3>{raid.status==="won"&&me.phase!=="out"?"A new legend, written together.":"Courage is worth another try."}</h3><p>{raid.status==="won"&&me.phase!=="out"?`${selected.badge} · ${300+selected.level*15} coins · ${200+selected.level*20} active XP + 20% for the crew. Your crew is restored.`:"Accept rescue to restore your crew at the Healing Lodge."}</p><button className="primary-button" disabled={busy} onClick={()=>void run(async()=>{const result=await rpc<Save>("nuvori_league_claim",{raid:raid.id});if(!validateSave(result))throw new Error("The saved result could not be read. Please keep this room open and retry.");onResult(result);onRaid(null);onClose();})}>{busy?"Saving rewards…":raid.status==="won"&&me.phase!=="out"?"Collect crest & return":"Accept rescue"}</button></div>
      :<><div className="raid-log" aria-live="polite">{raid.log.slice(-4).map((line,i)=><p key={`${raid.revision}-${i}`}>{line}</p>)}</div>{me.phase==="choice"?<div className="last-stand-choice"><Shield/><h3>Your crew has fallen. Will you step in?</h3><p>Make a last stand as your keeper, or call for a rescue.</p><button className="primary-button" disabled={busy} onClick={()=>act("stand")}>I’ll fight myself</button><button className="secondary-button" disabled={busy} onClick={()=>act("withdraw")}>Call for rescue</button></div>:me.phase==="keeper"?<div className="battle-actions"><button disabled={busy} onClick={()=>act("strike")}><Swords/> Courage Strike</button><button disabled={busy} onClick={()=>act("brace")}><Shield/> Brace · 70% protection</button><button disabled={busy} onClick={()=>act("withdraw")}>Call for rescue</button></div>:<><div className="battle-moves">{leader.moves.map(id=><button key={id} disabled={busy||leader.pp[id]<=0} style={{borderColor:TYPE_COLORS[MOVE_BY_ID[id].type]}} onClick={()=>act("move",id)}><strong>{MOVE_BY_ID[id].name}</strong><span>{MOVE_BY_ID[id].type} · {leader.pp[id]} PP</span></button>)}</div><div className="raid-switch">{me.party.map((n,i)=><button key={n.uid} disabled={busy||i===me.active||n.hp<=0} onClick={()=>act("switch",String(i))}><NuvoArt id={n.speciesId} size={42}/>{SPECIES_BY_ID[n.speciesId].name}<small>{n.hp} HP</small></button>)}</div><button className="text-button" disabled={busy} onClick={()=>act("withdraw")}>Withdraw from this trial</button></>}<p className="muted">Act once every 2 seconds. The guardian retaliates after each move or switch; status ailments do not linger on guardians.</p></>}
    </>:<p>Restoring this Champions room…</p>}
  </Modal>;
}
