import {useEffect,useRef,useState,type CSSProperties} from "react";
import {ArrowRight,Check,ChevronLeft,ChevronRight,Gift,Lock,Sparkles,Zap} from 'lucide-react';
import {Modal} from "./components";
import type {Save} from "./game";
import {SEASON,PASS_REWARDS,passTier,claimPassReward,activatePassBoost} from "./season";
import {ORBS} from "./expansion";
import {gameAudio} from "./audio";
import {RewardArtwork} from './RewardArtwork';
import {menuProgress} from './menuModel';
import './seasonMenu.css';
export function SeasonPass({save,onChange,onClose,onBegin}:{save:Save|null;onChange:(s:Save)=>void;onClose:()=>void;onBegin?:()=>void}){
 const [page,setPage]=useState(Math.min(9,Math.floor((save?passTier(save):0)/10))),[selected,setSelected]=useState(100),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[celebrate,setCelebrate]=useState(0);
 const m=menuProgress(save,now),p=m.progress,tier=m.tier,reward=PASS_REWARDS[selected-1],claimed=p.claimed.includes(selected),unlocked=Boolean(save)&&tier>=selected;
 const showcase=useRef<HTMLDivElement>(null);
 const preview=(next:number)=>{setSelected(next);setError('');requestAnimationFrame(()=>{showcase.current?.focus({preventScroll:true});showcase.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});};
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const apply=(fn:()=>Save)=>{try{onChange(fn());setError('');setCelebrate(v=>v+1);gameAudio.play('purchase');}catch(e){setError((e as Error).message);}};
 const active=now>=SEASON.starts&&now<SEASON.ends;
 return <Modal title={`Season 1 · ${SEASON.name}`} eyebrow="THE FREE SEASON PASS · 100 TIERS" onClose={onClose} wide>
 <div className="season-view">
 <section className="season-cinematic"><div className="season-moon"/><div className="season-stars"/><img src={`${import.meta.env.BASE_URL}assets/menu-solunelle.png`} alt="Solunelle, the exclusive tier 100 mythical"/><div><span className="eyebrow">{SEASON.subtitle}</span><h3>Catch the<br/><em>first light.</em></h3><p>100 free rewards. One extraordinary bond.</p><span className="season-dates">OCT 09, 2026 — JAN 09, 2027 · UTC</span></div><span className="season-free">ALL TIERS FREE <Sparkles size={12}/></span></section>
 <div className="season-progress-panel"><span className="season-tier-medal">{tier}<small>TIER</small></span><div><div><strong>{save?`Your season journey${m.available?` · ${m.available} unclaimed`:''}`:'Preview the season'}</strong><span>{p.xp.toLocaleString()} / 30,000 XP</span></div><progress max={30000} value={p.xp} aria-label="Season pass experience"/><small>{!save?'Create your keeper to start earning rewards.':!active?'Season closed. Earned rewards remain claimable.':tier===100?'Your First Light journey is complete.':`${300-p.xp%300} XP to tier ${tier+1} · ${m.daysLeft} days remain`}</small></div><button className="season-boost" disabled={!save||!active||!p.boosts||tier===100} onClick={()=>save&&apply(()=>activatePassBoost(save))}><Zap size={17}/><span>2× PASS XP<small>{p.boostUntil>now&&active?`${Math.ceil((p.boostUntil-now)/60000)}m active`: `${p.boosts} boost${p.boosts===1?'':'s'} available`}</small></span></button></div>
 <div className="season-showcase" key={selected} ref={showcase} tabIndex={-1} role="region" aria-label={`Tier ${selected}: ${reward.name} preview`}><div className="showcase-art"><i/><i/><RewardArtwork reward={reward} size={190} save={save}/>{celebrate>0&&claimed&&<span key={celebrate} className="reward-burst">✦</span>}</div><div className="showcase-copy"><span className="eyebrow">TIER {selected} · {reward.kind==='nuvo'?'EXCLUSIVE MYTHICAL':reward.kind==='cosmetic'?'EXCLUSIVE STYLE':'TRAIL SUPPLIES'}</span><h4>{reward.kind==='orbs'?ORBS.find(o=>o.id===reward.orb)?.name:reward.name}</h4><p>{reward.kind==='nuvo'?'A celestial fox-dragon with a leaf-woven tail carrying the first stars of the season. Solunelle joins your crew at level 5.':reward.kind==='cosmetic'?'A lasting memento of First Light. Previewed on your keeper; equip your claimed style at Thread & Thistle.':reward.kind==='boost'?'Double season XP for 30 real-time minutes. Boosts stack duration and never expire while waiting in your inventory.':`${reward.amount} ${reward.kind==='coins'?'coins to spend on your next adventure':reward.kind==='potions'?'restoring potions to keep your crew ready':'orbs for new companions on the trail'}.`}</p><button disabled={Boolean(save)&&(!unlocked||claimed)} onClick={()=>save?apply(()=>claimPassReward(save,selected)):onBegin?.()}>{!save?'Begin your adventure':claimed?'Reward claimed':unlocked?'Claim reward':`Unlock at tier ${selected}`}{claimed?<Check size={15}/>:unlocked||!save?<ArrowRight size={15}/>:<Lock size={14}/>}</button></div></div>
 {error&&<p className="season-error" role="alert">{error}</p>}
 <div className="season-track-heading"><div><span className="eyebrow">THE REWARD ROAD</span><h4>Every step brings something new.</h4></div><button onClick={()=>{const next=PASS_REWARDS.find(r=>r.tier<=tier&&!p.claimed.includes(r.tier))?.tier??Math.min(100,tier+1);setPage(Math.floor((next-1)/10));preview(next);}}>Your next reward <ArrowRight size={13}/></button></div>
 <nav className="season-pages" aria-label="Reward pages"><button aria-label="Previous reward page" disabled={page===0} onClick={()=>setPage(v=>v-1)}><ChevronLeft size={16}/></button>{Array.from({length:10},(_,i)=><button key={i} aria-pressed={page===i} onClick={()=>setPage(i)}>{i*10+1}–{i*10+10}</button>)}<button aria-label="Next reward page" disabled={page===9} onClick={()=>setPage(v=>v+1)}><ChevronRight size={16}/></button></nav>
 <div className="season-track">{PASS_REWARDS.slice(page*10,page*10+10).map(r=>{const collected=p.claimed.includes(r.tier),ready=tier>=r.tier&&Boolean(save);return <button key={r.tier} className={`season-reward ${r.kind==='nuvo'||r.kind==='cosmetic'?'rare-reward':''} ${ready?'unlocked':''} ${collected?'claimed':''}`} style={{'--reward-delay':`${(r.tier%10)*-.3}s`} as CSSProperties} aria-pressed={selected===r.tier} aria-label={`Tier ${r.tier}: ${r.name}${collected?', claimed':ready?', ready to claim':', locked'}`} onClick={()=>{preview(r.tier);gameAudio.play('ui-click');}}><span className="reward-tier">{r.tier}<i>{collected?<Check size={11}/>:ready?<Gift size={11}/>:<Lock size={10}/>}</i></span><RewardArtwork reward={r} size={86} save={save}/><strong>{r.kind==='orbs'?ORBS.find(o=>o.id===r.orb)?.name:r.name}</strong><small>{r.kind==='nuvo'?'MYTHICAL':r.kind==='cosmetic'?'EXCLUSIVE':`×${r.amount}`}</small><span className="reward-state">{collected?'CLAIMED':ready?'READY TO CLAIM':'PREVIEW'}</span></button>;})}</div>
 <details className="season-how"><summary>How to earn XP & use rewards</summary><p>Battles: 75 XP · New species: 125 · Discoveries: 150 · First trainer win: +150 · Champions rewards: 300. Boosts double pass XP for 30 real-time minutes and stack duration. Claimed styles stay yours after the season. Rewards and progress follow your adventure save.</p></details>
 </div>
 </Modal>;
}
